<a href="https://colab.research.google.com/github/chohoon901/DataAnalysis_1/blob/main/sunghuncho/ch05_01%2B02_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array((1,2,3))

array([1, 2, 3])

In [6]:
np.array(range(1,4))

array([1, 2, 3])

In [12]:
np.array([c for c in "123"],dtype="i")

array([1, 2, 3], dtype=int32)

In [13]:
arr=np.array([1,2,3])


In [14]:
type(arr)

numpy.ndarray

## 벡터와 연산

In [18]:
a=list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
a+10

TypeError: ignored

In [21]:
[v+2 for v in a]

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [17]:
a=np.array(range(10))
a+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
arr=np.arange(10)

In [28]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
arr+np.ones_like(arr)*2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
(((arr*5)//2)-1)%7

array([6, 1, 4, 6, 2, 4, 0, 2, 5, 0])

In [31]:
arr==5

array([False, False, False, False, False,  True, False, False, False,
       False])

In [32]:
arr[arr==5]

array([5])

In [33]:
arr[arr>5] # 정수 인덱싱

array([6, 7, 8, 9])

In [34]:
np.where(arr>5)

(array([6, 7, 8, 9]),)

In [35]:
arr2=np.arange(6,25,2)

In [36]:
np.where(arr2%3==0)

(array([0, 3, 6, 9]),)

In [37]:
arr2[np.where(arr2%3==0)]
# 불리언 인덱싱(불리언 인덱싱이 조건을 통해 
# 정수 인덱싱보다 광범위한 범위의 값을 쉽게 찾을수 있지만, 정수 인덱싱은 
# 세세한 값을 일일히 찾을때 좋다.)

array([ 6, 12, 18, 24])

In [38]:
arr[(arr>5)|(arr%2==0)]

array([0, 2, 4, 6, 7, 8, 9])

In [39]:
np.array([[1,2,3,4],[1,2,3,4]])

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [40]:
np.array([[1,2,3,4],[1,2,3]]) # 행들간 열의 크기가 같아야함

<ipython-input-40-aefd4c916d56>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2,3,4],[1,2,3]])


array([list([1, 2, 3, 4]), list([1, 2, 3])], dtype=object)

In [41]:
a1=np.array([[1,2,3,4],[1,2,3,4]])

In [42]:
a1[1,1]

2

In [43]:
a1.ndim,a1.shape

(2, (2, 4))

In [45]:
m=np.array([[1,2], [3,4]])
m2=np.array([range(2,4), range(5,7)])
print(m)
print(m2)

[[1 2]
 [3 4]]
[[2 3]
 [5 6]]


In [48]:
t=np.array([
    [
     [3,5,2],
     [3,5,2],
     [3,5,2]
    ],[
     [3,5,2],
     [3,5,2],
     [3,5,2]
    ]
])
t

array([[[3, 5, 2],
        [3, 5, 2],
        [3, 5, 2]],

       [[3, 5, 2],
        [3, 5, 2],
        [3, 5, 2]]])

In [47]:
t.ndim,t.shape

(3, (2, 3, 3))

In [57]:
a=np.arange(10).reshape(2,-1) # -1이 자동으로 열을 계산해줌

In [51]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
b=a
b[1,4]=7

In [55]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 7]])

In [56]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 7]])

In [59]:
b=a.copy()
b[1,4]=7
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 7]]


In [68]:
a=range(1,100,25)
print(a)

range(1, 100, 25)


In [60]:
a=np.arange(1,100,25)
a

array([ 1, 26, 51, 76])

In [62]:
a[3],a[-1],a[len(a)-1]

(76, 76, 76)

In [63]:
m=np.arange(6).reshape((2,-1))

In [64]:
m

array([[0, 1, 2],
       [3, 4, 5]])

In [66]:
m[0,2]

2

In [71]:
m[-2,-1],m[0:0,0:0]

(2, array([], shape=(0, 0), dtype=int64))

In [98]:
m[:,0] # 모든 행, 모든 열 -> 콜론( : )을 넣어줌

array([0, 3])

In [100]:
m[:,(0,2)]

array([[0, 2],
       [3, 5]])

## 배열의 자료형

In [101]:
x=np.array([1,2,3])
x.dtype

dtype('int64')

In [102]:
x=np.array([1.0,2,3])
x.dtype

dtype('float64')

In [103]:
x=np.array([1.0,2,"3"])
x.dtype
# 평소의 배열은 타입을 알아서 추론해서 배정
# 그러나 dtype으로 명시적으로 타입을 배정하지 않으면 

dtype('<U32')

In [104]:
x1=np.array([1,2,3],dtype="i")
x2=np.array([1,2,3],dtype=int)
x1.dtype
x2.dtype

dtype('int64')

In [105]:
x1=np.array([1,2,3.5],dtype="i")
x1

array([1, 2, 3], dtype=int32)

In [106]:
a=np.zeros(5)
b=np.array([0,1,0,1,0])
a/b,b/a

<ipython-input-106-c2d7ac0bdaae>:3: RuntimeWarning: invalid value encountered in true_divide
  a/b,b/a
<ipython-input-106-c2d7ac0bdaae>:3: RuntimeWarning: divide by zero encountered in true_divide
  a/b,b/a


(array([nan,  0., nan,  0., nan]), array([nan, inf, nan, inf, nan]))

In [107]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [109]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [111]:
a=np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [112]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [113]:
np.ones_like(a)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [117]:
np.empty((2,5))

array([[3.29856565e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.05676078e-067],
       [6.11382021e+169, 3.21442654e-057, 7.42862364e-091,
        8.69891862e-043, 6.93451165e-310]])

In [119]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [121]:
np.logspace(1,10,5)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [122]:
A=np.arange(1,7).reshape(2,-1)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
A.ndim, A.shape

(2, (2, 3))

In [126]:
B=A.T
B

array([[1, 4],
       [2, 5],
       [3, 6]])

In [127]:
B.ndim, B.shape

(2, (3, 2))

In [129]:
A.flatten(),A.ravel()

(array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 4, 5, 6]))

In [132]:
t=np.arange(30).reshape(3,5,-1)
t

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [133]:
t.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [135]:
x=np.arange(5)
print(x,x.ndim,x.shape)
x2=x[:,np.newaxis]
print(x2,x2.ndim,x2.shape)
x3=x[np.newaxis,:]
print(x3,x3.ndim,x3.shape)

[0 1 2 3 4] 1 (5,)
[[0]
 [1]
 [2]
 [3]
 [4]] 2 (5, 1)
[[0 1 2 3 4]] 2 (1, 5)
