<a href="https://colab.research.google.com/github/chohoon901/DataAnalysis_1/blob/main/sunghuncho/ch05_04_%EA%B8%B0%EC%88%A0%ED%86%B5%EA%B3%84%2B%EB%82%9C%EC%88%98%EB%B0%9C%EC%83%9D%EA%B3%BC%2B%EC%B9%B4%EC%9A%B4%ED%8C%85_sunghuncho.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 기술 통계

## 기술 통계(descriptive statistics)
> 데이터 집합에 대해 통계를 계산
* 데이터의 개수(count)
* 평균(mean, average)
* 분산(variance)
* 표준 편차(standard deviation)
* 최댓값(maximum)
* 최솟값(minimum)
* 중앙값(median)
* 사분위수(quartile)

In [1]:
import numpy as np

In [5]:
x=np.array([
    18,5,10,23,19,-8,10,0,0,5,2,15,8,
    2,5,4,15,-1,4,-7,-24,7,9,-6,23,-13
])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

## 데이터의 개수

In [6]:
len(x)

26

## 표본 평균
* 우리가 일반적으로 아는 평균
* 통계용어로는 표본 평균(sample average, sample mean)
<br>
$
\bar{x} = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{x_i}
$
(𝑁은 데이터의 개수)

In [7]:
np.mean(x)

4.8076923076923075

## 표본 분산
* 표본 분산(sample variance) : 데이터와 표본 평균간의 거리의 제곱의 평균
* 표본 분산이 작으면 데이터가 모여있는 것이고 크면 흩어져 있는 것
<br>
$
s^2 = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{(x_i-\bar{x})^2}
$

In [10]:
s=np.var(x)
s

115.23224852071006

## 표본 표준편차
* 표본 표준편차(sample standard variance) : 표본 분산의 양의 제곱근 값 
<br>
$
s = \sqrt{s^2}
$

In [12]:
np.sqrt(s),np.std(x)

(10.734628476137871, 10.734628476137871)

## 최댓값과 최솟값

In [21]:
# 최댓값 (maximum) / 최솟값 (minimum)
np.max(x),np.min(x)

(23, -24)

## 중앙값
* 중앙값(median) : 데이터를 크기대로 정렬하였을 때 가장 가운데에 있는 수
* 만약 데이터의 수가 짝수이면 가장 가운데에 있는 두 수의 평균을 사용


In [22]:
np.median(x)

5.0

## 사분위수
* 사분위수(quartile) : 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수
* 각각 1사분위수, 2사분위수, 3사분위수라고 함
* 1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%
* 따라서 2사분위수는 중앙값과 같음
* 때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 함
* 1사분위수는 25% 백분위수와 같음


In [15]:
np.percentile(x,0) # 최솟값

-24.0

In [16]:
np.percentile(x,25)

0.0

In [18]:
np.percentile(x,50)

5.0

In [17]:
np.percentile(x,75)

10.0

In [20]:
np.percentile(x,100) # 최댓값

23.0

# 난수 발생과 카운팅

## 시드 설정
* 컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아님
* 어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성. 이런 시작 숫자를 시드(seed)라고 함
* 일단 생성된 난수는 다음번 난수 생성을 위한 시드값이 됨. 따라서 시드값은 한 번만 정해주면 됨.
* 시드는 보통 현재 시각 등을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있음 * 특정한 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있음
* 고정된 결과를 얻기 위해서 실습엔 시드를 설정

In [23]:
a=np.random.seed(0) # 시드값 고정

### `rand` : 0과 1 사이의 난수를 발생

In [25]:
np.random.rand(5) # rand(n) : 0과 1사이 n개의 랜덤값을 가지는 배열

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [26]:
np.random.rand(10)

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

## 데이터의 순서 변경

### `shuffle`
* 데이터의 순서를 변경
* 자체 변환(in-place) 함수 (원본에 영향)

In [27]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.random.shuffle(x)
x

array([8, 0, 1, 6, 2, 4, 7, 9, 3, 5])

## 데이터 샘플링
* 표본선택 혹은 샘플링(sampling) : 이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것

### `choice` : 샘플링에 사용
```
numpy.random.choice(a, size=None, replace=True, p=None)
```
* a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
* size : 정수. 샘플 숫자
* replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능 (복원/비복원 추출)
* p : 배열. 각 데이터가 선택될 수 있는 확률

In [44]:
np.random.choice(5,5) # 기본적으로 복원추출

array([1, 2, 3, 3, 3])

In [38]:
np.random.choice(5,5,replace=False) # 비복원 추출 (한번 뽑은건 다시 못뽑음)

array([3, 0, 2, 1, 4])

In [37]:
np.random.choice(5,5,replace=True) # 복원 추출 (한번 뽑은것도 다시 뽑기 가능)

array([3, 2, 3, 0, 3])

In [40]:
np.random.choice(5,10,replace=True)

array([3, 2, 0, 1, 1, 3, 0, 0, 1, 2])

In [48]:
np.random.choice(5,10,p=[0.1,0,0.3,0.6,0]) # p : 각 데이터의 확률 지정

array([2, 3, 2, 3, 3, 3, 3, 3, 3, 3])

## 난수 생성
* `rand` : 0부터 1 사이의 균일 분포
* `randn` : 표준 정규 분포
* `randint` : 균일 분포의 정수 난수

### `rand` : 0부터 1 사이에서 균일한 확률 분포로 실수 난수를 생성
* 숫자 인수는 생성할 난수의 크기
* 여러 개의 인수를 넣으면 해당 크기를 가진 행렬을 생성

In [50]:
np.random.rand(10)

array([0.6439902 , 0.42385505, 0.60639321, 0.0191932 , 0.30157482,
       0.66017354, 0.29007761, 0.61801543, 0.4287687 , 0.13547406])

In [51]:
np.random.rand(3,5)

array([[0.29828233, 0.56996491, 0.59087276, 0.57432525, 0.65320082],
       [0.65210327, 0.43141844, 0.8965466 , 0.36756187, 0.43586493],
       [0.89192336, 0.80619399, 0.70388858, 0.10022689, 0.91948261]])

### `randn` : 기댓값이 0이고 표준편차가 1인 표준 정규 분포(standard normal distribution)를 따르는 난수를 생성

In [56]:
np.random.randn(10)

array([ 1.71334272, -0.74475482, -0.82643854, -0.09845252, -0.66347829,
        1.12663592, -1.07993151, -1.14746865, -0.43782004, -0.49803245])

In [57]:
np.random.randn(3,5)

array([[ 1.92953205,  0.94942081,  0.08755124, -1.22543552,  0.84436298],
       [-1.00021535, -1.5447711 ,  1.18802979,  0.31694261,  0.92085882],
       [ 0.31872765,  0.85683061, -0.65102559, -1.03424284,  0.68159452]])

### `randint`
```
numpy.random.randint(low, high=None, size=None)
```
만약 `high`를 입력하지 않으면 0과 `low`사이의 숫자, `high`를 입력하면 `low`와 `high`는 사이의 숫자를 출력. `size`는 난수의 숫자

In [59]:
np.random.randint(1,5,2)

array([1, 3])

In [64]:
np.random.randint(10,20,10)

array([15, 10, 10, 13, 11, 19, 19, 16, 16, 17])

In [66]:
np.random.randint(10,20,15).reshape(3,-1)

array([[16, 11, 17, 14, 19],
       [12, 10, 18, 12, 17],
       [18, 14, 14, 11, 17]])

## 💡 연습문제 7
1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 작성하라
2. 주사위를 100번 던져서 나오는 숫자의 평균
3. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [ ]:
# 1.


array(['TAIL', 'TAIL', 'HEAD', 'HEAD', 'HEAD', 'HEAD', 'TAIL', 'TAIL',
       'TAIL', 'HEAD'], dtype='<U4')

In [ ]:
# 2.


3.66

In [ ]:
# 3.


array([-0.00317543, -0.01632423, -0.00067134,  0.01489356,  0.00521304,
        0.00611927, -0.01341497,  0.00476898,  0.0014845 ,  0.00529045,
        0.00422629, -0.01359781, -0.00041401, -0.00757871, -0.00050084,
       -0.00897401,  0.0131247 , -0.00858972, -0.00898942,  0.00074586,
       -0.01077099, -0.00424663, -0.00829965,  0.01411172,  0.00785804,
       -0.0005747 , -0.00391217,  0.00940918,  0.00405204,  0.00498052,
       -0.00026192, -0.0168823 , -0.00112466, -0.0053249 ,  0.00645055,
        0.01011842, -0.00657951,  0.00468385,  0.01735879, -0.00667713,
        0.01681922, -0.00852586,  0.0002296 , -0.00011146,  0.00011499,
       -0.00837678, -0.00591183, -0.0066772 ,  0.00326963,  0.00330035,
        0.02225944,  0.01370989, -0.00509843,  0.0032487 ,  0.00997118,
        0.00030602, -0.00069642,  0.00051575,  0.00867277, -0.00848321,
       -0.00325669,  0.00470433,  0.00311447,  0.00239583, -0.00369801,
        0.00972536,  0.02133868,  0.00406415, -0.00193177,  0.00

array([ 9968.24569061,  9805.52172515,  9798.93887103,  9944.87995133,
        9996.72298327, 10057.89564959,  9922.96930879,  9970.29178757,
        9985.09264399, 10037.91830117, 10080.34141693,  9943.27087728,
        9939.15428244,  9863.82832836,  9858.88811928,  9770.41436592,
        9898.64815922,  9813.6215047 ,  9725.40272392,  9732.65655233,
        9627.82619918,  9586.94035449,  9507.37214356,  9641.53752326,
        9717.30109408,  9711.71660794,  9673.72271651,  9764.74447753,
        9804.31162059,  9853.14223038,  9850.56147198,  9684.2613353 ,
        9673.36983564,  9621.86011642,  9683.9264325 ,  9781.91250933,
        9717.55231377,  9763.06789394,  9932.54293905,  9866.22208637,
       10032.16422056,  9946.63140825,  9948.91513051,  9947.80626305,
        9948.95015133,  9865.60998051,  9807.28616123,  9741.80092199,
        9773.65296712,  9805.90945388, 10024.18353955, 10161.61399384,
       10109.8056916 , 10142.64937851, 10243.78355919, 10246.91834384,
      

## 정수 데이터 카운팅
* 만약 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석

### `unique`
* unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력
* return_counts 인수를 True 로 설정하면 각 값을 가진 데이터 갯수도 출력


In [67]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [69]:
a=np.array(['a','b','b','c','a'])
index,count=np.unique(a,return_counts=True)

In [70]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [71]:
count

array([2, 2, 1])

In [72]:
dict(zip(*np.unique(a,return_counts=True)))

{'a': 2, 'b': 2, 'c': 1}

### `bincount`
* `unique` 함수는 데이터에 존재하는 값에 대해서만 갯수를 세므로 데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 정보를 주지 않음
* 따라서 데이터가 주사위를 던졌을 때 나오는 수처럼 특정 범위안의 수인 경우에는 `bincount` 함수에 `minlength` 인수를 설정하여 쓰는 것이 더 편리
* `bincount` 함수는 0 부터 `minlength` - 1 까지의 숫자에 대해 각각 카운트
* 데이터가 없을 경우에는 카운트 값이 0이 됨

In [73]:
np.bincount([1,1,2,2,2,3],minlength=6)

array([0, 2, 3, 1, 0, 0])