<a href="https://colab.research.google.com/github/chohoon901/DataAnalysis_1/blob/main/sunghuncho/ch05_02%2B03%2B04_%EB%B3%B5%EC%8A%B5_sunghuncho.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1, 4) # 1, 2, 3
arr2 = np.arange(4, 7) # 4, 5, 6
np.concatenate([arr1, arr2], axis=0)

array([1, 2, 3, 4, 5, 6])

In [3]:
np.concatenate([arr1,arr2,arr1,arr2])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [8]:
a=arr1.reshape(3,1)
b=arr2.reshape(3,1)

np.concatenate([a,b], axis=0)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [7]:
np.concatenate([a,b], axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
a1=np.ones((2,3))
a2=np.zeros((2,2))
np.hstack((a1,a2))

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [12]:
a2=np.zeros((3,3))
np.vstack((a1,a2))

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
a2=np.zeros((2,3))
np.dstack((a1,a2))

array([[[1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.]]])

In [15]:
c = np.stack([a1,a2], axis=0) # 행기준
c

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
np.stack([a1,a2], axis=1)

array([[[1., 1., 1.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [0., 0., 0.]]])

In [18]:
np.stack([a1,a2], axis=2)

array([[[1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.]]])

In [20]:
np.r_[np.arange(1,4), np.arange(4,7)] # r_ = hstack

array([1, 2, 3, 4, 5, 6])

In [23]:
np.c_[np.arange(1,4), np.arange(4,7)] # c_ = vstack

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
a=np.arange(1,4)[:, np.newaxis]
b=np.arange(4,7)[:, np.newaxis]

In [30]:
np.concatenate((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [31]:
a = np.arange(6).reshape(2, -1)
np.tile(a, 3), np.repeat(a, 3)

(array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5, 3, 4, 5]]),
 array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5]))

In [32]:
arr=np.arange(7)

In [33]:
np.array_split(arr,3)

[array([0, 1, 2]), array([3, 4]), array([5, 6])]

In [37]:
arr=np.arange(6)
np.split(arr,3) # 약수로 정확하게 쪼개지 않으면 오류

[array([0, 1]), array([2, 3]), array([4, 5])]

In [38]:
arr=np.arange(1,19).reshape(-1,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [41]:
# np.array_split(arr,3)
np.array_split(arr,3,axis=1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]), array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]), array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [42]:
x=np.arange(5)

In [43]:
x+np.full_like(x,10) # x에 10으로 가득찬 배열을 더한다

array([10, 11, 12, 13, 14])

In [45]:
x=np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [47]:
y=np.arange(5).reshape(5,-1)
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [48]:
x+y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [49]:
x=np.arange(1,5)

In [50]:
x.argmin(),x.argmax()

(0, 3)

In [51]:
x.mean() # 평균

2.5

In [52]:
np.median(x) # 중간값

2.5

In [54]:
np.any(x>4),np.any(x>2)

(False, True)

In [55]:
np.all(x>4),np.all(x>0)

(False, True)

In [56]:
x=np.array(((1,1),(2,2)))

In [57]:
x

array([[1, 1],
       [2, 2]])

In [60]:
x.sum(),x.sum(axis=0),x.sum(axis=1)

(6, array([3, 3]), array([2, 4]))

In [76]:
a=np.random.randint(1,20,12).reshape(3,-1)
a

array([[13, 13, 10, 10],
       [15,  8,  6, 18],
       [18, 12, 14, 13]])

In [63]:
np.sort(a)

array([[ 3, 13, 19, 19],
       [ 4,  4, 11, 12],
       [ 2,  4,  8, 17]])

In [66]:
np.sort(a,axis=0)

array([[ 4,  3,  4,  2],
       [ 8, 11,  4, 12],
       [19, 17, 19, 13]])

In [74]:
a=np.arange(4)
b=np.tile(a,(3,1))
b

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [75]:
np.argsort(b,axis=0)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [79]:
a[:,np.argsort(a[1])]

array([[10, 13, 13, 10],
       [ 6,  8, 15, 18],
       [14, 12, 18, 13]])

In [80]:
a=np.random.randint(-30,30,20)
a

array([ -7,  -6, -30,  16, -12, -15,  22,  24,   0,   1,  29,  -6,  28,
        -7, -17, -25, -25,   8,   9,  23])

In [83]:
len(a)

20

In [84]:
np.mean(a)

0.5

In [86]:
np.var(a)

329.45

In [88]:
np.std(a)

18.15075755994774

In [89]:
np.max(a),np.min(a)

(29, -30)

In [91]:
np.median(a)

-3.0

In [95]:
np.quantile(a,0),np.percentile(a,0)

(-30, -30.0)

In [96]:
np.quantile(a,0.25),np.percentile(a,25)

(-12.75, -12.75)

In [97]:
np.quantile(a,0.5),np.percentile(a,50)

(-3.0, -3.0)

In [98]:
np.quantile(a,0.75),np.percentile(a,75)

(17.5, 17.5)

In [100]:
np.quantile(a,1.0),np.percentile(a,100)

(29.0, 29.0)

In [101]:
x=np.arange(10)

In [102]:
np.random.shuffle(x)

In [103]:
x

array([8, 0, 7, 4, 6, 3, 5, 1, 9, 2])

In [105]:
np.random.choice(x,5,replace=False)

array([9, 4, 8, 5, 2])

In [106]:
np.random.choice(x,5,replace=True)

array([8, 1, 7, 7, 2])

In [112]:
np.random.choice(np.arange(1,46),5,replace=False)

array([29,  3, 31, 45,  4])

In [113]:
x

array([8, 0, 7, 4, 6, 3, 5, 1, 9, 2])

In [111]:
np.random.choice(x,5,p=[0,0,0,0,0,0,0,0.5,0,0.5])

array([1, 2, 2, 1, 1])

In [115]:
np.random.randn(10)

array([ 0.38754062, -0.63639275,  1.18493343, -0.92343338, -0.7093522 ,
        1.23884373, -0.86169016,  0.27872344,  1.46289031,  0.01408208])

In [116]:
np.random.randint(10)

9

In [118]:
np.random.randint(10,20)

14

In [120]:
np.random.randint(10,20,3) 


array([13, 18, 11])

In [ ]:
price=10000
days=250
daily_earning_rate=np.random.randn(days)/100
price_arr=np.empty(days)
for i,v in enumerate(daily_earning_rate):
  price*=(1+v)
  price_arr[i]=price
price_arr

In [124]:
x=np.random.randint(1,10,100)
x

array([6, 4, 4, 4, 9, 7, 6, 4, 3, 8, 9, 1, 3, 1, 8, 5, 2, 1, 5, 3, 5, 5,
       6, 2, 6, 3, 6, 5, 7, 6, 8, 8, 5, 5, 6, 2, 1, 7, 9, 9, 3, 2, 4, 6,
       8, 1, 7, 7, 4, 6, 9, 5, 2, 6, 6, 2, 4, 6, 8, 1, 5, 9, 4, 1, 2, 2,
       6, 4, 8, 4, 7, 5, 5, 5, 4, 5, 1, 6, 4, 9, 2, 5, 9, 8, 4, 6, 5, 8,
       2, 4, 1, 5, 6, 4, 9, 1, 3, 7, 5, 2])

In [125]:
np.unique(x)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
np.unique(x,return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11,  6, 15, 17, 16,  7,  9,  9]))

In [130]:
key,value=np.unique(x,return_counts=True)
print(key)
print(value)

[1 2 3 4 5 6 7 8 9]
[10 11  6 15 17 16  7  9  9]


In [132]:
list(zip(key,value)) # zip : 2개의 시퀸스를 인덱스로 묶어준다

[(1, 10), (2, 11), (3, 6), (4, 15), (5, 17), (6, 16), (7, 7), (8, 9), (9, 9)]

In [134]:
dict(list(zip(key,value)))

{1: 10, 2: 11, 3: 6, 4: 15, 5: 17, 6: 16, 7: 7, 8: 9, 9: 9}

In [137]:
dict(zip(*np.unique(x,return_counts=True)))

{1: 10, 2: 11, 3: 6, 4: 15, 5: 17, 6: 16, 7: 7, 8: 9, 9: 9}

In [138]:
x=np.random.randint(30,size=10)
x

array([26, 14, 12, 12,  6, 11,  0, 14, 27, 26])

In [139]:
dict(zip(*np.unique(x,return_counts=True)))

{0: 1, 6: 1, 11: 1, 12: 2, 14: 2, 26: 2, 27: 1}

In [141]:
np.bincount(x,minlength=30)

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 2, 1, 0, 0])

In [142]:
dict(zip(np.arange(30),np.bincount(x,minlength=30)))

{0: 1,
 1: 0,
 2: 0,
 3: 0,
 4: 0,
 5: 0,
 6: 1,
 7: 0,
 8: 0,
 9: 0,
 10: 0,
 11: 1,
 12: 2,
 13: 0,
 14: 2,
 15: 0,
 16: 0,
 17: 0,
 18: 0,
 19: 0,
 20: 0,
 21: 0,
 22: 0,
 23: 0,
 24: 0,
 25: 0,
 26: 2,
 27: 1,
 28: 0,
 29: 0}